apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p1tj9dy1d-go
  janus-idp.io/tekton: p1tj9dy1d-go
  backstage.io/kubernetes-id: p1tj9dy1d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p1tj9dy1d-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
