apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p1tj9dy1d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p1tj9dy1d-go 
  name: p1tj9dy1d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: p1tj9dy1d-go 
